"""add meeting and payment tables

Revision ID: 7a41ae562185
Revises: 9b571b115977
Create Date: 2026-03-02 20:35:40.680840

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a41ae562185'
down_revision = '9b571b115977'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('meetings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_user_id', sa.Integer(), nullable=False),
    sa.Column('meeting_type', sa.Enum('TWO_BY_TWO', 'THREE_BY_THREE', name='meeting_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('RECRUITING', 'FULL', 'WAITING_CONFIRM', 'CONFIRMED', name='meeting_status_enum'), nullable=False),
    sa.ForeignKeyConstraint(['host_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meetings_status'), 'meetings', ['status'], unique=False)
    op.create_table('chat_rooms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', name='uq_chat_room_meeting')
    )
    op.create_index(op.f('ix_chat_rooms_meeting_id'), 'chat_rooms', ['meeting_id'], unique=False)
    op.create_table('confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'user_id', name='uq_confirmation_meeting_user')
    )
    op.create_index(op.f('ix_confirmations_meeting_id'), 'confirmations', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_confirmations_user_id'), 'confirmations', ['user_id'], unique=False)
    op.create_table('deposits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('REQUIRED', 'PENDING', 'HELD', 'REFUNDED', 'FORFEITED', 'CANCELED', name='deposit_status_enum'), nullable=False),
    sa.Column('toss_order_id', sa.String(length=64), nullable=False),
    sa.Column('toss_payment_key', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposits_meeting_id'), 'deposits', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_deposits_status'), 'deposits', ['status'], unique=False)
    op.create_index(op.f('ix_deposits_toss_order_id'), 'deposits', ['toss_order_id'], unique=True)
    op.create_index(op.f('ix_deposits_user_id'), 'deposits', ['user_id'], unique=False)
    op.create_table('meeting_slots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('team', sa.Enum('MALE', 'FEMALE', name='meeting_team_enum'), nullable=False),
    sa.Column('slot_index', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'team', 'slot_index', name='uq_slot_position')
    )
    op.create_index(op.f('ix_meeting_slots_meeting_id'), 'meeting_slots', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_slots_user_id'), 'meeting_slots', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_meeting_slots_user_id'), table_name='meeting_slots')
    op.drop_index(op.f('ix_meeting_slots_meeting_id'), table_name='meeting_slots')
    op.drop_table('meeting_slots')
    op.drop_index(op.f('ix_deposits_user_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_toss_order_id'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_status'), table_name='deposits')
    op.drop_index(op.f('ix_deposits_meeting_id'), table_name='deposits')
    op.drop_table('deposits')
    op.drop_index(op.f('ix_confirmations_user_id'), table_name='confirmations')
    op.drop_index(op.f('ix_confirmations_meeting_id'), table_name='confirmations')
    op.drop_table('confirmations')
    op.drop_index(op.f('ix_chat_rooms_meeting_id'), table_name='chat_rooms')
    op.drop_table('chat_rooms')
    op.drop_index(op.f('ix_meetings_status'), table_name='meetings')
    op.drop_table('meetings')
    # ### end Alembic commands ###