"""init schema

Revision ID: 9b571b115977
Revises: 
Create Date: 2026-03-02 19:48:27.244917

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b571b115977'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('phone_hash', sa.String(length=64), nullable=False),
    sa.Column('phone_last4', sa.String(length=4), nullable=False),
    sa.Column('phone_verified', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('verification_status', sa.Enum('PENDING', 'VERIFIED', 'REJECTED', name='verification_status_enum'), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', name='gender_enum'), nullable=True),
    sa.Column('university', sa.String(length=100), nullable=True),
    sa.Column('major', sa.String(length=100), nullable=True),
    sa.Column('entry_year', sa.Integer(), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('preferred_area', sa.String(length=100), nullable=True),
    sa.Column('bio_short', sa.String(length=40), nullable=True),
    sa.Column('lookalike_type', sa.Enum('CELEB', 'ANIMAL', name='lookalike_type_enum'), nullable=True),
    sa.Column('lookalike_value', sa.String(length=60), nullable=True),
    sa.Column('photo_url_1', sa.Text(), nullable=True),
    sa.Column('photo_url_2', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_hash'), 'users', ['phone_hash'], unique=True)
    op.create_index(op.f('ix_users_verification_status'), 'users', ['verification_status'], unique=False)
    op.create_table('verification_docs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('doc_type', sa.Enum('ENROLLMENT_CERT', 'STUDENT_ID', name='doc_type_enum'), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('SUBMITTED', 'REVIEWED', name='doc_status_enum'), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_docs_user_id'), 'verification_docs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_docs_user_id'), table_name='verification_docs')
    op.drop_table('verification_docs')
    op.drop_index(op.f('ix_users_verification_status'), table_name='users')
    op.drop_index(op.f('ix_users_phone_hash'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###