"""add replacement_requests

Revision ID: a7c097f14993
Revises: cb3e840285c8
Create Date: 2026-03-03 20:46:38.714731

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c097f14993'
down_revision = 'cb3e840285c8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('replacement_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('meeting_id', sa.Integer(), nullable=False),
    sa.Column('leaver_user_id', sa.Integer(), nullable=False),
    sa.Column('candidate_user_id', sa.Integer(), nullable=False),
    sa.Column('attempt_no', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'EXPIRED', 'CANCELED', name='replacement_status_enum'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['leaver_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['meeting_id'], ['meetings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('meeting_id', 'leaver_user_id', 'attempt_no', name='uq_replacement_attempt')
    )
    op.create_index('ix_replacement_candidate_user_id', 'replacement_requests', ['candidate_user_id'], unique=False)
    op.create_index('ix_replacement_meeting_id', 'replacement_requests', ['meeting_id'], unique=False)
    op.drop_constraint('uq_chat_rooms_meeting', 'chat_rooms', type_='unique')
    op.drop_constraint('uq_confirmations_meeting_user', 'confirmations', type_='unique')
    op.drop_constraint('uq_deposits_meeting_user', 'deposits', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_deposits_meeting_user', 'deposits', ['meeting_id', 'user_id'])
    op.create_unique_constraint('uq_confirmations_meeting_user', 'confirmations', ['meeting_id', 'user_id'])
    op.create_unique_constraint('uq_chat_rooms_meeting', 'chat_rooms', ['meeting_id'])
    op.drop_index('ix_replacement_meeting_id', table_name='replacement_requests')
    op.drop_index('ix_replacement_candidate_user_id', table_name='replacement_requests')
    op.drop_table('replacement_requests')
    # ### end Alembic commands ###