"""add confirmed to meeting_slots

Revision ID: e30f40bf0561
Revises: cf195490b285
Create Date: 2026-03-05 23:02:06.773858

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30f40bf0561'
down_revision = 'cf195490b285'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'meeting_slots',
        sa.Column('confirmed', sa.Boolean(), nullable=False, server_default=sa.false())
    )
    op.alter_column('meetings', 'preferred_universities_any',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('meetings', 'preferred_universities_any',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('meeting_slots', 'confirmed')
    # ### end Alembic commands ###